// PROBLEM 2: Find the sum of all the even-valued terms in the Fibonacci
// sequence which do not exceed four million.
//
// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// Find the sum of all the even-valued terms in the sequence which do not
// exceed four million.

#include <stdio.h>

int main() {
    // a and b are the last two calculated terms in the Fibonacci sequence
    int a = 1;
    int b = 2;

    int last;       // temporary
    int sum = 0;    // running total

    while (b < 4000000) {
        if (b % 2 == 0)
            sum += b;
        
        // Move a to last, b to a, and change b to the next term
        last = a;
        a = b;
        b = last + a;
    }
        
    printf("%d\n", sum);

    return 0;
}
